In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
import re

In [ ]:
url = "https://raw.githubusercontent.com/KatiaMusun/etl-seguros-pipeline/refs/heads/main/data/raw/polizas.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [ ]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

Limpieza de datos

In [ ]:
polizas = df.copy()

In [ ]:
polizas.columns = polizas.columns.str.strip().str.lower()

In [ ]:
for col in polizas.select_dtypes(include='object').columns:
    polizas[col] = polizas[col].astype(str).str.strip()

In [ ]:
polizas = polizas.replace(r'^\s*$', pd.NA, regex=True)

In [ ]:
polizas = polizas.drop_duplicates()

Transformciones

In [ ]:
polizas['fecha_emision'] = pd.to_datetime(
    polizas['fecha_emision'],
    errors='coerce'
)

In [ ]:

def limpiar_numero_mixto(valor):
    if pd.isna(valor):
        return pd.NA  # mantener nulos

    # convertir a string
    valor = str(valor)

    # quitar comas, espacios, etc.
    valor = re.sub(r'[^\d.]', '', valor)

    try:
        return float(valor)
    except:
        return pd.NA

In [ ]:
polizas["prima"] = polizas["prima"].apply(limpiar_numero_mixto)
polizas["comision"] = polizas["comision"].apply(limpiar_numero_mixto)
polizas["monto_asegurado"] = polizas["monto_asegurado"].apply(limpiar_numero_mixto)

In [ ]:
cols = ["prima", "comision", "monto_asegurado"]

for col in cols:
    polizas[col] = polizas[col].astype(str).str.replace(r'[^\d.]', '', regex=True)
    polizas[col] = pd.to_numeric(polizas[col], errors='coerce')

Separar válidos y rechazados

In [ ]:
validos = polizas[
    polizas['fecha_emision'].notna() &
    polizas['prima'].notna() &
    polizas['monto_asegurado'].notna()
].copy()

In [ ]:
rechazados = polizas[
    polizas['fecha_emision'].isna() |
    polizas['prima'].isna() |
    polizas['monto_asegurado'].isna()
].copy()

Motivo de rechazo

In [ ]:
def motivo(row):
    motivos = []

    if pd.isna(row['fecha_emision']):
        motivos.append("fecha_invalida")

    if pd.isna(row['prima']):
        motivos.append("prima_invalida")

    if pd.isna(row['monto_asegurado']):
        motivos.append("monto_invalido")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [ ]:
validos.to_csv("polizas_curated.csv", index=False)
rechazados.to_csv("polizas_rejects.csv", index=False)

Conectar con PostgreSQL cloud

In [ ]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_bv09_user:fCW2NoAjuwpUmvjVY8MbpEYPss9XKGza@dpg-d6qu8cf5gffc73f0e5l0-a.oregon-postgres.render.com/etl_seguros_bv09"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 93.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [ ]:
validos.to_sql(
    'polizas_curated',
    engine,
    if_exists='append',
    index=False
)

922

In [ ]:
rechazados.to_sql(
    'polizas_rejects',
    engine,
    if_exists='append',
    index=False
)

228

In [ ]:
pd.read_sql(
"SELECT COUNT(*) FROM polizas_curated LIMIT 10",
engine
)

   count
0   2922

In [ ]:
pd.read_sql(
"SELECT id_aseguradora, COUNT(*) FROM polizas_curated GROUP BY id_aseguradora LIMIT 10",
engine
)

   id_aseguradora  count
0               4    178
1              14    175
2               3    213
3              10    172
4               9    191
5               7    210
6              13    209
7               1    190
8               5    214
9               2    205