In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/KatiaMusun/etl-seguros-pipeline/refs/heads/main/data/raw/siniestros.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [ ]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

Limpieza de datos

In [ ]:
siniestros = df.copy()

In [ ]:
siniestros.columns = siniestros.columns.str.strip().str.lower()

In [ ]:
for col in siniestros.select_dtypes(include="object").columns:siniestros[col] = siniestros[col].str.strip()

In [ ]:
siniestros = siniestros.replace(r'^\s*$', pd.NA, regex=True)

In [ ]:
siniestros = siniestros.drop_duplicates()

Transformciones

In [ ]:
siniestros = siniestros.replace({
    'ABIERTO': 'Abierto'
})

In [ ]:
def convertir_fecha_multiple(columna):
    # convertir a string y limpiar espacios
    columna = columna.astype(str).str.strip()

    # convertir a datetime (maneja múltiples formatos)
    return pd.to_datetime(
        columna,
        errors='coerce',
        dayfirst=True
    )

In [ ]:
siniestros["fecha_siniestro"] = convertir_fecha_multiple(siniestros["fecha_siniestro"])

In [ ]:
import re

def limpiar_numero_mixto(valor):
    # mantener nulos
    if pd.isna(valor):
        return pd.NA

    # convertir a string
    valor = str(valor).strip()

    # eliminar todo lo que no sea número o punto decimal
    valor = re.sub(r'[^\d.]', '', valor)

    # convertir a número
    try:
        return float(valor)
    except:
        return pd.NA

In [ ]:
siniestros["monto_siniestro"] = siniestros["monto_siniestro"].apply(limpiar_numero_mixto)

In [ ]:
map_estado = {
    "abierto": "Abierto",
    "cerrado": "Cerrado",
    "en proceso": "En Proceso",
    "pendiente": "Pendiente"
}

In [ ]:
siniestros["estado"] = siniestros["estado"].str.strip().str.lower().map(map_estado)

In [ ]:
siniestros["estado"] = siniestros["estado"].fillna("No especificado")

Separar datos validos y rechazados

In [ ]:
validos = siniestros[
    siniestros['fecha_siniestro'].notna() &
    siniestros['monto_siniestro'].notna()
    & siniestros['estado'].notna()
].copy()

In [ ]:
rechazados = siniestros[
    siniestros['fecha_siniestro'].isna() |
    siniestros['monto_siniestro'].isna() |
    siniestros['estado'].isna()

].copy()

Motivo de rechazo

In [ ]:
def motivo(row):
    motivos = []

    if pd.isna(row['fecha_siniestro']):
        motivos.append("fecha_invalida")

    if pd.isna(row['monto_siniestro']):
        motivos.append("monto_invalido")

    if pd.isna(row['estado']):
        motivos.append("estado_invalido")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

Exportar archivos

In [ ]:
validos.to_csv("siniestros_curated.csv", index=False)
rechazados.to_csv("siniestros_rejects.csv", index=False)

Conectar con PostgreSQL cloud

In [ ]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine


database_url = "postgresql://etl_seguros_bv09_user:fCW2NoAjuwpUmvjVY8MbpEYPss9XKGza@dpg-d6qu8cf5gffc73f0e5l0-a.oregon-postgres.render.com/etl_seguros_bv09"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 40.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [ ]:
validos.to_sql(
    'siniestros_curated',
    engine,
    if_exists='append',
    index=False
)

739

In [ ]:
rechazados.to_sql(
    'siniestros_rejects',
    engine,
    if_exists='append',
    index=False
)

881

consulta sql

In [ ]:
pd.read_sql(
" SELECT estado, COUNT(*) FROM siniestros_curated GROUP BY estado LIMIT 10",
engine
)

            estado  count
0          Cerrado    231
1  No especificado    304
2          Abierto    204

In [ ]:
pd.read_sql(
" SELECT SUM (monto_siniestro) FROM siniestros_curated",
engine
)

            sum
0  4.490015e+06