In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 447, in run
    conflicts = self._determine_conflicts(to_install)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 578, in _determine_conflicts
    return check_install_conflicts(to_install)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/operations/check.py", line 101, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/operations/check.py", line 39, in create_package_set_from_installed
    for dist in env.iter_installed_distributions(local_only=False, skip=()):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/base.py", line 664, in <genexpr>
    return (d for d in it if d.canonical_name not in skip)
                       ^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    yield from finder.find(location)
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 79, in find
    for dist, info_location in self._find_impl(location):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 61, in _find_impl
    for dist in importlib.metadata.distributions(path=[location]):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 354, in __new__
    if getattr(getattr(cls, name), '__isabstractmethod__', False)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/main.py", line 80, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 100, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 232, in _main
    return run(options, args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 215, in exc_logging_wrapper
    logger.critical("Operation cancelled by user")
  File "/usr/lib/python3.12/logging/__init__.py", line 1586, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/utils/logging.py", line 172, in emit
    style = Style(color="red")
            ^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
^C

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/KatiaMusun/etl-seguros-pipeline/refs/heads/main/data/raw/clientes.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [ ]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_cliente        3030 non-null   int64
 1   nombre            3030 non-null   object
 2   email             3030 non-null   object
 3   genero            2435 non-null   object
 4   fecha_nacimiento  3030 non-null   object
 5   ciudad            3030 non-null   object
 6   segmento          2433 non-null   object
dtypes: int64(1), object(6)
memory usage: 165.8+ KB

id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

Limpieza de datos

In [ ]:
cliente = df.copy()

In [ ]:
cliente.columns = cliente.columns.str.strip().str.lower()

In [ ]:
for col in cliente.select_dtypes(include='object').columns:
    cliente[col] = cliente[col].astype(str).str.strip()

In [ ]:
clientes = cliente.replace(r'^\s*$', pd.NA, regex=True)

In [ ]:
cliente['email'] = cliente['email'].str.lower()

In [ ]:
cliente['fecha_nacimiento'] = pd.to_datetime(cliente['fecha_nacimiento'], errors='coerce')

In [ ]:
cliente = cliente.drop_duplicates()

trasformaciones

In [ ]:
cliente['segmento'] = cliente['segmento'].replace({
    'REGULAR': 'Regular',
    'PYME': 'Pyme',
    'VIP': 'Vip',
    'PREMIUM': 'Premium'

})

In [ ]:
cliente['genero'] = cliente['genero'].replace({
    'Hombre': "Masculino",
  'hombre': "Masculino",
    'masculino': "Masculino",
    'm': "Masculino",
    'mujer': "Femenino",
    'femenino': "Femenino",
    'f': "Femenino"

})

In [ ]:
cliente['ciudad'] = cliente['ciudad'].replace({
     'sanmiguel': "San Miguel",
     'SanMiguel': "San Miguel",
    's. miguel': "San Miguel",
      'S. Miguel': "San Miguel",
    'san miguel': "San Miguel",
    'sta.ana': "Santa Ana",
     'Sta. Ana': "Santa Ana",
    'sta ana': "Santa Ana",
    'santa ana': "Santa Ana",
    'ss': "San Salvador",
    'san salvador': "San Salvador"

})

In [ ]:
cliente['ciudad'] = cliente['ciudad'].str.replace(
    r'([a-z])([A-Z])', r'\1 \2', regex=True
)

Separar datos validos y rechazados

In [ ]:
validos = cliente[
    cliente['nombre'].notna() &
    cliente['email'].notna()
].copy()

In [ ]:
rechazados = cliente[
    cliente['nombre'].isna() |
    cliente['email'].isna()
].copy()

Motivo de rechazo

In [ ]:
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['email']):
        motivos.append("email_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

Exportar archivos

In [ ]:
validos.to_csv("cliente_curated.csv", index=False)

In [ ]:
rechazados.to_csv("cliente_rejects.csv", index=False)

Conectar con PostgreSQL cloud

In [ ]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_bv09_user:fCW2NoAjuwpUmvjVY8MbpEYPss9XKGza@dpg-d6qu8cf5gffc73f0e5l0-a.oregon-postgres.render.com/etl_seguros_bv09"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 48.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

Cargar datos en PostgreSQL

In [ ]:
validos.to_sql(
    'cliente_curated',
    engine,
    if_exists='append',
    index=False
)

30

In [ ]:
rechazados.to_sql(
    'cliente_rejects',
    engine,
    if_exists='append',
    index=False
)

0

Consulta sql

In [ ]:
pd.read_sql(
"SELECT * FROM cliente_curated LIMIT 10",
engine
)

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Masculino,2011-11-24,San Miguel,nan
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,nan,NaT,Santa Ana,nan
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,NaT,San Miguel,nan
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,NaT,La Libertad,Regular
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,nan,1945-08-02,San Salvador,Pyme
5,6,Ricardo López Vásquez,ricardo.lopez.vasquez6@seguro.sv,Masculino,1966-10-15,sonsonate,Pyme
6,7,Diego Flores Rojas,diego.flores.rojas0@example.com,Masculino,NaT,Santa Ana,Premium
7,8,Karla Ortiz López,karla.ortiz.lopez1@mail.com,M,NaT,Santa Ana,Premium
8,9,Juan Flores Morales,juan.flores.morales2@example.com,Femenino,NaT,San Miguel,Regular
9,10,María Aguilar López,maria.aguilar.lopez3@example.com,Masculino,NaT,San Salvador,Premium